server.port=${PORT:8085}
spring.datasource.url=jdbc:postgresql://dpg-d9ufli2dbo9c73eueu8g-a.oregon-postgres.render.com:5432/comprago?sslmode=require
spring.datasource.username=${DATABASE_USER:comprago}
spring.datasource.password=${DATABASE_PASSWORD:Comprago2026!}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
