server.port=${PORT:8084}
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/comprago_orders}
spring.datasource.username=${DATABASE_USER:comprago}
spring.datasource.password=${DATABASE_PASSWORD:comprago123}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.servlet.multipart.enabled=true
