server.port=8086
spring.datasource.url=jdbc:postgresql://localhost:5432/comprago_cart
spring.datasource.username=comprago
spring.datasource.password=comprago123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
