server.port=${PORT:8081}

auth-service.url=${AUTH_URL:http://localhost:8080}
sellers-service.url=${SELLERS_URL:http://localhost:8082}
products-service.url=${PRODUCTS_URL:http://localhost:8083}
inventory-service.url=${INVENTORY_URL:http://localhost:8084}
search-service.url=${SEARCH_URL:http://localhost:8085}
cart-service.url=${CART_URL:http://localhost:8086}
orders-service.url=${ORDERS_URL:http://localhost:8087}
payments-service.url=${PAYMENTS_URL:http://localhost:8088}
shipping-service.url=${SHIPPING_URL:http://localhost:8089}
customers-service.url=${CUSTOMERS_URL:http://localhost:8090}
